### PR TITLE
Fix includes + config in decicated + regex

### LINKED ISSUE #2: Improve route name matching with regex
I want to use regex to include or exclude named routes in the configuration file.

### LINKED ISSUE #12: Include not exclude the rest
Hi,
Here is the config in "app.php" (we should use a separate config file)
```
'jsroutes' => [
        'name' => 'routes.js',
        'include' => [
            'admin.clients.autocomplete'
        ],
        'exclude' => [
            //
        ],
        'methods' => [
            //
        ],
    ]
```

With this config "includeRoute" in CreateJSRoutesCommand.php always return true

I made a pull request for the fix of both

### PR DESCRIPTION
**Pull request by dansleboby**
Fix includes should be overwriting all and put config in decicated file instand of app.php + fallback on the old

### CODE REVIEW

**Comment by halivert** [comment]
Hey! this is a great improvement, thank you so much 😌

File: src/Console/CreateJSRoutesCommand.php [hunk 1]
```diff
@@ -96,26 +97,31 @@ public function createFile($fileName, $contents)
...
 	private function includeRoute($route, $routeName)
 	{
-		$include = $this->getOption('include');
+        $include = $this->getOption('include');
 
-		if (in_array($routeName, $include)) {
-			return true;
-		}
+        if(!empty($include)) {
+            return Str::is($include, $routeName);
```
Comment (halivert) [inline src/Console/CreateJSRoutesCommand.php:103]: I didn't know `Str::is` accepts an array as first argument, but is very nice 👍🏽

**Comment by halivert** [comment]
Also I spotted an issue, the keys `include`, `exclude` and `methods` shouldn't be mutually exclusive, to be more flexible
